# Generated by Django 4.2.17 on 2025-01-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock', models.PositiveIntegerField()),
                ('product_category', models.CharField(choices=[('casual', 'Casual Shoes'), ('formal', 'Formal Shoes'), ('sports', 'Sports Shoes'), ('kids', 'Kids Shoes')], max_length=20)),
                ('product_image1', models.ImageField(upload_to='products/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_head', models.CharField(max_length=255, verbose_name='Heading')),
                ('add_sub_head', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subheading')),
                ('add_text', models.TextField(blank=True, null=True, verbose_name='Text Description')),
                ('add_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('add_image', models.ImageField(upload_to='slider_images/', verbose_name='Image')),
            ],
        ),
    ]
